---
kind: pipeline
name: testing
type: docker
slack:
  where: false

steps:
  - name: test
    image: node:16-alpine
    commands:
      - npm ci
      - npm run lint
      - npm run test

trigger:
  ref:
    - refs/heads/develop
    - "refs/tags/**"
    - "refs/pull/**"

---
kind: pipeline
name: deploy
type: docker

steps:
  - name: dry-run
    pull: always
    image: plugins/docker
    settings:
      dry_run: true
      repo: ghcr.io/goodwillaz/drone-slack
      registry: ghcr.io
      username: goodwillaz-ci
      password:
        from_secret: gh_token
    when:
      event:
        - pull_request

  - name: publish
    image: plugins/docker
    settings:
      auto_tag: true
      repo: ghcr.io/goodwillaz/drone-slack
      registry: ghcr.io
      username: goodwillaz-ci
      password:
        from_secret: gh_token
    when:
      event:
        exclude:
          - pull_request

trigger:
  ref:
    - refs/heads/develop
    - "refs/tags/**"
    - "refs/pull/**"

depends_on:
  - testing
